//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace feedsea.BackgroundAgent.Common.Resources
{
   using System;

   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   internal class Strings
   {

      internal Strings()
      {
      }

      /// <summary>
      ///   Looks up a localized string similar to Uncategorized.
      /// </summary>
      internal static string Uncategorized
      {
         get
         {
            return GetString("Uncategorized");
         }
      }

      private static string GetString(string key)
      {
         Windows.ApplicationModel.Resources.ResourceLoader loader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView("Strings");
         return loader.GetString(key);
      }

   }

}