//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace feedsea.Resources
{
   using System;

   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   public class AppResources
   {

      internal AppResources()
      {
      }

      /// <summary>
      ///   Looks up a localized string similar to About.
      /// </summary>
      public static string About
      {
         get
         {
            return GetString("About");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to &lt;Add new category&gt;.
      /// </summary>
      public static string AddNewCategory
      {
         get
         {
            return GetString("AddNewCategory");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Add Source.
      /// </summary>
      public static string AddSource
      {
         get
         {
            return GetString("AddSource");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Add to Favorites.
      /// </summary>
      public static string AddToFavorites
      {
         get
         {
            return GetString("AddToFavorites");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to day ago.
      /// </summary>
      public static string AgoDay
      {
         get
         {
            return GetString("AgoDay");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to days ago.
      /// </summary>
      public static string AgoDays
      {
         get
         {
            return GetString("AgoDays");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to hour ago.
      /// </summary>
      public static string AgoHour
      {
         get
         {
            return GetString("AgoHour");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to hours ago.
      /// </summary>
      public static string AgoHours
      {
         get
         {
            return GetString("AgoHours");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to minute ago.
      /// </summary>
      public static string AgoMinute
      {
         get
         {
            return GetString("AgoMinute");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to minutes ago.
      /// </summary>
      public static string AgoMinutes
      {
         get
         {
            return GetString("AgoMinutes");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to second ago.
      /// </summary>
      public static string AgoSecond
      {
         get
         {
            return GetString("AgoSecond");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to seconds ago.
      /// </summary>
      public static string AgoSeconds
      {
         get
         {
            return GetString("AgoSeconds");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to All Articles.
      /// </summary>
      public static string AllArticles
      {
         get
         {
            return GetString("AllArticles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to feedsea.
      /// </summary>
      public static string ApplicationTitle
      {
         get
         {
            return GetString("ApplicationTitle");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Normal.
      /// </summary>
      public static string ArticleLayoutType_Normal
      {
         get
         {
            return GetString("ArticleLayoutType_Normal");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Normal without Image.
      /// </summary>
      public static string ArticleLayoutType_NormalNoImage
      {
         get
         {
            return GetString("ArticleLayoutType_NormalNoImage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Small.
      /// </summary>
      public static string ArticleLayoutType_Small
      {
         get
         {
            return GetString("ArticleLayoutType_Small");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Small without Image.
      /// </summary>
      public static string ArticleLayoutType_SmallNoImage
      {
         get
         {
            return GetString("ArticleLayoutType_SmallNoImage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Go to the Article.
      /// </summary>
      public static string ArticleNavigatePage
      {
         get
         {
            return GetString("ArticleNavigatePage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Attention.
      /// </summary>
      public static string Attention
      {
         get
         {
            return GetString("Attention");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Pause.
      /// </summary>
      public static string AudioFile_Pause
      {
         get
         {
            return GetString("AudioFile_Pause");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Play.
      /// </summary>
      public static string AudioFile_Play
      {
         get
         {
            return GetString("AudioFile_Play");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Playing.
      /// </summary>
      public static string AudioFile_Playing
      {
         get
         {
            return GetString("AudioFile_Playing");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Back to Top.
      /// </summary>
      public static string BackToTop
      {
         get
         {
            return GetString("BackToTop");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Internet Explorer.
      /// </summary>
      public static string BrowserSelect_InternetExplorer
      {
         get
         {
            return GetString("BrowserSelect_InternetExplorer");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Maxthon.
      /// </summary>
      public static string BrowserSelect_MaxthonBrowser
      {
         get
         {
            return GetString("BrowserSelect_MaxthonBrowser");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Nokia Xpress.
      /// </summary>
      public static string BrowserSelect_NokiaXpress
      {
         get
         {
            return GetString("BrowserSelect_NokiaXpress");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to UC Browser.
      /// </summary>
      public static string BrowserSelect_UCBrowser
      {
         get
         {
            return GetString("BrowserSelect_UCBrowser");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Cancel.
      /// </summary>
      public static string Cancel
      {
         get
         {
            return GetString("Cancel");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Categories.
      /// </summary>
      public static string Categories
      {
         get
         {
            return GetString("Categories");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Category.
      /// </summary>
      public static string Category
      {
         get
         {
            return GetString("Category");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Category Name.
      /// </summary>
      public static string CategoryName
      {
         get
         {
            return GetString("CategoryName");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Click to Login.
      /// </summary>
      public static string ClickToLogin
      {
         get
         {
            return GetString("ClickToLogin");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Disable Ads.
      /// </summary>
      public static string DisableAds
      {
         get
         {
            return GetString("DisableAds");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Edit.
      /// </summary>
      public static string Edit
      {
         get
         {
            return GetString("Edit");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Edit Source.
      /// </summary>
      public static string EditSource
      {
         get
         {
            return GetString("EditSource");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enter the source URL.
      /// </summary>
      public static string EnterSourceUrl
      {
         get
         {
            return GetString("EnterSourceUrl");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enter the url of the source.
      /// </summary>
      public static string EnterUrlOfSource
      {
         get
         {
            return GetString("EnterUrlOfSource");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Featured Articles.
      /// </summary>
      public static string FeaturedArticles
      {
         get
         {
            return GetString("FeaturedArticles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to 1 day.
      /// </summary>
      public static string Item_Days_1
      {
         get
         {
            return GetString("Item_Days_1");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to 3 days (recommended).
      /// </summary>
      public static string Item_Days_3
      {
         get
         {
            return GetString("Item_Days_3");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to 5 days.
      /// </summary>
      public static string Item_Days_5
      {
         get
         {
            return GetString("Item_Days_5");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to 7 days.
      /// </summary>
      public static string Item_Days_7
      {
         get
         {
            return GetString("Item_Days_7");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Article list items Layout.
      /// </summary>
      public static string Lbl_ArticleListItemLayout
      {
         get
         {
            return GetString("Lbl_ArticleListItemLayout");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Ask before marking all articles read.
      /// </summary>
      public static string Lbl_AskBeforeMarkingAllRead
      {
         get
         {
            return GetString("Lbl_AskBeforeMarkingAllRead");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Categories.
      /// </summary>
      public static string Lbl_Categories
      {
         get
         {
            return GetString("Lbl_Categories");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Choose view.
      /// </summary>
      public static string Lbl_ChooseView
      {
         get
         {
            return GetString("Lbl_ChooseView");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Google Mobilizer.
      /// </summary>
      public static string Lbl_ChooseView_Google
      {
         get
         {
            return GetString("Lbl_ChooseView_Google");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Google Mobilizer without Images.
      /// </summary>
      public static string Lbl_ChooseView_GoogleNoImg
      {
         get
         {
            return GetString("Lbl_ChooseView_GoogleNoImg");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Instapaper Mobilizer.
      /// </summary>
      public static string Lbl_ChooseView_Instapaper
      {
         get
         {
            return GetString("Lbl_ChooseView_Instapaper");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Readability Mobilizer.
      /// </summary>
      public static string Lbl_ChooseView_Readability
      {
         get
         {
            return GetString("Lbl_ChooseView_Readability");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Open web page.
      /// </summary>
      public static string Lbl_ChooseView_WebPage
      {
         get
         {
            return GetString("Lbl_ChooseView_WebPage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Create new category.
      /// </summary>
      public static string Lbl_CreateNewCategory
      {
         get
         {
            return GetString("Lbl_CreateNewCategory");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Download full article if there&apos;s only summary using.
      /// </summary>
      public static string Lbl_DownloadArticleIfNoContent
      {
         get
         {
            return GetString("Lbl_DownloadArticleIfNoContent");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Instapaper.
      /// </summary>
      public static string Lbl_DownloadContent_Instapaper
      {
         get
         {
            return GetString("Lbl_DownloadContent_Instapaper");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Readability.
      /// </summary>
      public static string Lbl_DownloadContent_Readability
      {
         get
         {
            return GetString("Lbl_DownloadContent_Readability");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enable Instapaper.
      /// </summary>
      public static string Lbl_Enable_Instapaper
      {
         get
         {
            return GetString("Lbl_Enable_Instapaper");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enable OneNote.
      /// </summary>
      public static string Lbl_Enable_OneNote
      {
         get
         {
            return GetString("Lbl_Enable_OneNote");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enable Pocket.
      /// </summary>
      public static string Lbl_Enable_Pocket
      {
         get
         {
            return GetString("Lbl_Enable_Pocket");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enable Live Tiles.
      /// </summary>
      public static string Lbl_EnableLiveTiles
      {
         get
         {
            return GetString("Lbl_EnableLiveTiles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Hide AppBar on Article Page.
      /// </summary>
      public static string Lbl_HideAppBarArticlePage
      {
         get
         {
            return GetString("Lbl_HideAppBarArticlePage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Hide AppBar on Main Feed.
      /// </summary>
      public static string Lbl_HideAppBarMainPage
      {
         get
         {
            return GetString("Lbl_HideAppBarMainPage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to What browser would you like to open article links on?.
      /// </summary>
      public static string Lbl_LinkBrowserSelect
      {
         get
         {
            return GetString("Lbl_LinkBrowserSelect");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to live tiles.
      /// </summary>
      public static string Lbl_LiveTiles
      {
         get
         {
            return GetString("Lbl_LiveTiles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to From which category should articles be loaded when the app is started?.
      /// </summary>
      public static string Lbl_LoadCategoryOnLoad
      {
         get
         {
            return GetString("Lbl_LoadCategoryOnLoad");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Login.
      /// </summary>
      public static string Lbl_Login
      {
         get
         {
            return GetString("Lbl_Login");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Mark article read when opened.
      /// </summary>
      public static string Lbl_MarkArticleReadWhenOpened
      {
         get
         {
            return GetString("Lbl_MarkArticleReadWhenOpened");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Mark articles read on feed scroll.
      /// </summary>
      public static string Lbl_MarkReadOnFeedScroll
      {
         get
         {
            return GetString("Lbl_MarkReadOnFeedScroll");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Warning: More internet connection usage while scrolling..
      /// </summary>
      public static string Lbl_MarkReadOnFeedScroll_Warning
      {
         get
         {
            return GetString("Lbl_MarkReadOnFeedScroll_Warning");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to New category name.
      /// </summary>
      public static string Lbl_NewCategoryName
      {
         get
         {
            return GetString("Lbl_NewCategoryName");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Open YouTube links on MetroTube.
      /// </summary>
      public static string Lbl_OpenYoutubeOnMetroTube
      {
         get
         {
            return GetString("Lbl_OpenYoutubeOnMetroTube");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Password.
      /// </summary>
      public static string Lbl_Password
      {
         get
         {
            return GetString("Lbl_Password");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Phone.
      /// </summary>
      public static string Lbl_PhoneSettings
      {
         get
         {
            return GetString("Lbl_PhoneSettings");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Search.
      /// </summary>
      public static string Lbl_Search
      {
         get
         {
            return GetString("Lbl_Search");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Search Results.
      /// </summary>
      public static string Lbl_SearchResults
      {
         get
         {
            return GetString("Lbl_SearchResults");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to About.
      /// </summary>
      public static string Lbl_SettingsPage_About
      {
         get
         {
            return GetString("Lbl_SettingsPage_About");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Version {0}.
      /// </summary>
      public static string Lbl_SettingsPage_About_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_About_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Appearance.
      /// </summary>
      public static string Lbl_SettingsPage_Appearance
      {
         get
         {
            return GetString("Lbl_SettingsPage_Appearance");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Change app theme, feed list style and more..
      /// </summary>
      public static string Lbl_SettingsPage_Appearance_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_Appearance_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Disable Ads.
      /// </summary>
      public static string Lbl_SettingsPage_DisableAds
      {
         get
         {
            return GetString("Lbl_SettingsPage_DisableAds");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Disable Ads shown in the app..
      /// </summary>
      public static string Lbl_SettingsPage_DisableAds_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_DisableAds_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Feedback.
      /// </summary>
      public static string Lbl_SettingsPage_Feedback
      {
         get
         {
            return GetString("Lbl_SettingsPage_Feedback");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Send an email with feedback or bug reports..
      /// </summary>
      public static string Lbl_SettingsPage_Feedback_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_Feedback_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to General.
      /// </summary>
      public static string Lbl_SettingsPage_General
      {
         get
         {
            return GetString("Lbl_SettingsPage_General");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Hide read articles, download content and other reading settings..
      /// </summary>
      public static string Lbl_SettingsPage_General_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_General_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Live Tiles.
      /// </summary>
      public static string Lbl_SettingsPage_LiveTiles
      {
         get
         {
            return GetString("Lbl_SettingsPage_LiveTiles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enable/disable live tiles and change the appearance..
      /// </summary>
      public static string Lbl_SettingsPage_LiveTiles_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_LiveTiles_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Logout.
      /// </summary>
      public static string Lbl_SettingsPage_Logout
      {
         get
         {
            return GetString("Lbl_SettingsPage_Logout");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Log out from Feedly..
      /// </summary>
      public static string Lbl_SettingsPage_Logout_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_Logout_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Third Party.
      /// </summary>
      public static string Lbl_SettingsPage_ThirdParty
      {
         get
         {
            return GetString("Lbl_SettingsPage_ThirdParty");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Instapaper, Pocket, OneNote and more..
      /// </summary>
      public static string Lbl_SettingsPage_ThirdParty_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_ThirdParty_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Uservoice.
      /// </summary>
      public static string Lbl_SettingsPage_Uservoice
      {
         get
         {
            return GetString("Lbl_SettingsPage_Uservoice");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Feedback and support page..
      /// </summary>
      public static string Lbl_SettingsPage_Uservoice_Description
      {
         get
         {
            return GetString("Lbl_SettingsPage_Uservoice_Description");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Show articles from oldest to newest.
      /// </summary>
      public static string Lbl_ShowOldestToNewest
      {
         get
         {
            return GetString("Lbl_ShowOldestToNewest");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Show Phone Tray at top of Screen.
      /// </summary>
      public static string Lbl_ShowPhoneTrayAtTop
      {
         get
         {
            return GetString("Lbl_ShowPhoneTrayAtTop");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Show read articles on feed.
      /// </summary>
      public static string Lbl_ShowReadArticlesOnMainScreen
      {
         get
         {
            return GetString("Lbl_ShowReadArticlesOnMainScreen");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Show read if there are no unread articles.
      /// </summary>
      public static string Lbl_ShowReadIfNoUnread
      {
         get
         {
            return GetString("Lbl_ShowReadIfNoUnread");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Application Theme.
      /// </summary>
      public static string Lbl_Theme
      {
         get
         {
            return GetString("Lbl_Theme");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Dark.
      /// </summary>
      public static string Lbl_Theme_Dark
      {
         get
         {
            return GetString("Lbl_Theme_Dark");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Default.
      /// </summary>
      public static string Lbl_Theme_Default
      {
         get
         {
            return GetString("Lbl_Theme_Default");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Choose how you want your tiles to be presented..
      /// </summary>
      public static string Lbl_TileMode
      {
         get
         {
            return GetString("Lbl_TileMode");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to URL, Title or #topic.
      /// </summary>
      public static string Lbl_UrlTitleOrTopic
      {
         get
         {
            return GetString("Lbl_UrlTitleOrTopic");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Username (or Email).
      /// </summary>
      public static string Lbl_Username
      {
         get
         {
            return GetString("Lbl_Username");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Version.
      /// </summary>
      public static string Lbl_Version
      {
         get
         {
            return GetString("Lbl_Version");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to What client would you like to open YouTube videos on?.
      /// </summary>
      public static string Lbl_YoutubeClient
      {
         get
         {
            return GetString("Lbl_YoutubeClient");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to An error ocurred the last time you ran Feedsea, do you want to report us?.
      /// </summary>
      public static string LittleWatson_Message
      {
         get
         {
            return GetString("LittleWatson_Message");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Attention.
      /// </summary>
      public static string LittleWatson_Title
      {
         get
         {
            return GetString("LittleWatson_Title");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Loading....
      /// </summary>
      public static string Loading
      {
         get
         {
            return GetString("Loading");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Logout.
      /// </summary>
      public static string Logout
      {
         get
         {
            return GetString("Logout");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Are you sure you want to logout from your Feedly account? All Feedsea settings will be lost..
      /// </summary>
      public static string Logout_Message
      {
         get
         {
            return GetString("Logout_Message");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Mark all read.
      /// </summary>
      public static string MarkAllRead
      {
         get
         {
            return GetString("MarkAllRead");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Mark articles read.
      /// </summary>
      public static string MarkArticlesRead
      {
         get
         {
            return GetString("MarkArticlesRead");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Mark Read.
      /// </summary>
      public static string MarkRead
      {
         get
         {
            return GetString("MarkRead");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Mark Unread.
      /// </summary>
      public static string MarkUnread
      {
         get
         {
            return GetString("MarkUnread");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Feedsea is developed by.
      /// </summary>
      public static string Msg_About_DevelopedBy
      {
         get
         {
            return GetString("Msg_About_DevelopedBy");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Eric Mackrodt.
      /// </summary>
      public static string Msg_About_DeveloperName
      {
         get
         {
            return GetString("Msg_About_DeveloperName");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Follow on Twitter.
      /// </summary>
      public static string Msg_About_FollowTwitter
      {
         get
         {
            return GetString("Msg_About_FollowTwitter");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Review the app.
      /// </summary>
      public static string Msg_About_RateApp
      {
         get
         {
            return GetString("Msg_About_RateApp");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Send an email.
      /// </summary>
      public static string Msg_About_SendEmail
      {
         get
         {
            return GetString("Msg_About_SendEmail");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Want to give a feedback or tell me something else?.
      /// </summary>
      public static string Msg_About_SendFeedbackMessage
      {
         get
         {
            return GetString("Msg_About_SendFeedbackMessage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to I&apos;m using and recommend Feedsea as a news reader on Windows Phone (@feedsea).
      /// </summary>
      public static string Msg_About_ShareMessage
      {
         get
         {
            return GetString("Msg_About_ShareMessage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Share with your friends.
      /// </summary>
      public static string Msg_About_ShareWithFriends
      {
         get
         {
            return GetString("Msg_About_ShareWithFriends");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to This Live Tile is already pinned..
      /// </summary>
      public static string Msg_AlreadyPinned
      {
         get
         {
            return GetString("Msg_AlreadyPinned");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Cannot save a source without a title..
      /// </summary>
      public static string MSG_CannotSaveSourceWithoutTitle
      {
         get
         {
            return GetString("MSG_CannotSaveSourceWithoutTitle");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sorry&lt;br /&gt;There was a problem loading the login page, press back to retry or try again later..
      /// </summary>
      public static string Msg_CouldntLoadLoginPage
      {
         get
         {
            return GetString("Msg_CouldntLoadLoginPage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Couldn&apos;t load source, please verify the URL..
      /// </summary>
      public static string MSG_CouldntLoadSource
      {
         get
         {
            return GetString("MSG_CouldntLoadSource");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to How would you like to enable pocket?.
      /// </summary>
      public static string Msg_Enable_Pocket
      {
         get
         {
            return GetString("Msg_Enable_Pocket");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Enter a valid URL..
      /// </summary>
      public static string MSG_EnterValidURL
      {
         get
         {
            return GetString("MSG_EnterValidURL");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to It seems that you are new here, add sources to start reading your news..
      /// </summary>
      public static string Msg_Greetings_Message
      {
         get
         {
            return GetString("Msg_Greetings_Message");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Welcome!.
      /// </summary>
      public static string Msg_Greetings_Title
      {
         get
         {
            return GetString("Msg_Greetings_Title");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You have to enter a valid URL before loading..
      /// </summary>
      public static string MSG_HaveToEnterURLSourceBeforeLoading
      {
         get
         {
            return GetString("MSG_HaveToEnterURLSourceBeforeLoading");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You have to restart the app for these settings to take effect..
      /// </summary>
      public static string Msg_HaveToRestartToTakeEffect
      {
         get
         {
            return GetString("Msg_HaveToRestartToTakeEffect");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Feedsea received an unexpected response from Feedly. This might mean that Feedly is under maintenance or that you&apos;re connected to a network that needs authentication, have blocked content or uses a proxy server. If none of those are the case and this problem persists, try to logoff and login again..
      /// </summary>
      public static string Msg_HtmlResponse_Message
      {
         get
         {
            return GetString("Msg_HtmlResponse_Message");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Unexpected response from Feedly.
      /// </summary>
      public static string Msg_HtmlResponse_Title
      {
         get
         {
            return GetString("Msg_HtmlResponse_Title");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Are you sure you want to mark all current articles read?.
      /// </summary>
      public static string MSG_MarkCurrentArticlesReadConfirm
      {
         get
         {
            return GetString("MSG_MarkCurrentArticlesReadConfirm");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to There is nothing new right now. Try refreshing the feed..
      /// </summary>
      public static string Msg_NoArticlesAvailable
      {
         get
         {
            return GetString("Msg_NoArticlesAvailable");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Couldn&apos;t establish a connection right now. Verify your connection or try again later..
      /// </summary>
      public static string MSG_NoConnection
      {
         get
         {
            return GetString("MSG_NoConnection");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to It seems that you&apos;re new here, try adding new sources..
      /// </summary>
      public static string Msg_NoSourcesAvailable
      {
         get
         {
            return GetString("Msg_NoSourcesAvailable");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Pinning Live Tile.
      /// </summary>
      public static string Msg_PinningLiveTile
      {
         get
         {
            return GetString("Msg_PinningLiveTile");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to This action will remove the category but won&apos;t remove the sources within it. Are you sure you want to proceed?.
      /// </summary>
      public static string MSG_RemoveCategoryConfirmation
      {
         get
         {
            return GetString("MSG_RemoveCategoryConfirmation");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Are you sure you want to remove this article from saved articles?.
      /// </summary>
      public static string MSG_RemoveFromSaved
      {
         get
         {
            return GetString("MSG_RemoveFromSaved");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sending article to Instapaper.
      /// </summary>
      public static string Msg_SendingTo_Instapaper
      {
         get
         {
            return GetString("Msg_SendingTo_Instapaper");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Article sent to Instapaper successfully.
      /// </summary>
      public static string Msg_SendingTo_Instapaper_Done
      {
         get
         {
            return GetString("Msg_SendingTo_Instapaper_Done");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sending article to OneNote.
      /// </summary>
      public static string Msg_SendingTo_OneNote
      {
         get
         {
            return GetString("Msg_SendingTo_OneNote");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Article sent to OneNote successfully.
      /// </summary>
      public static string Msg_SendingTo_OneNote_Done
      {
         get
         {
            return GetString("Msg_SendingTo_OneNote_Done");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sending article to Pocket.
      /// </summary>
      public static string Msg_SendingTo_Pocket
      {
         get
         {
            return GetString("Msg_SendingTo_Pocket");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Article sent to Pocket successfully.
      /// </summary>
      public static string Msg_SendingTo_Pocket_Done
      {
         get
         {
            return GetString("Msg_SendingTo_Pocket_Done");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to There&apos;s already a source with the same URL, verify if you are not trying to add it again or try changing the title..
      /// </summary>
      public static string MSG_ThereIsSourceSameURL
      {
         get
         {
            return GetString("MSG_ThereIsSourceSameURL");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Updating Live Tiles.
      /// </summary>
      public static string Msg_UpdatingLiveTiles
      {
         get
         {
            return GetString("Msg_UpdatingLiveTiles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Wrong username or password, please try again..
      /// </summary>
      public static string Msg_WrongUsernameOrPassword
      {
         get
         {
            return GetString("Msg_WrongUsernameOrPassword");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You have to load a source before saving..
      /// </summary>
      public static string MSG_YouHaveToLoadSourceBeforeSaving
      {
         get
         {
            return GetString("MSG_YouHaveToLoadSourceBeforeSaving");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You have to restart the app to apply the theme. Click here to close the app..
      /// </summary>
      public static string Msg_YouHaveToRestartToApplyTheme
      {
         get
         {
            return GetString("Msg_YouHaveToRestartToApplyTheme");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to news.
      /// </summary>
      public static string News
      {
         get
         {
            return GetString("News");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to No.
      /// </summary>
      public static string No
      {
         get
         {
            return GetString("No");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Ok.
      /// </summary>
      public static string OK
      {
         get
         {
            return GetString("OK");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Open in the Browser.
      /// </summary>
      public static string OpenInBrowser
      {
         get
         {
            return GetString("OpenInBrowser");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Pin to Start screen.
      /// </summary>
      public static string PinToStartScreen
      {
         get
         {
            return GetString("PinToStartScreen");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to You have already purchased this product..
      /// </summary>
      public static string Purchase_AlreadyPurchased
      {
         get
         {
            return GetString("Purchase_AlreadyPurchased");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to The purchase was canceled..
      /// </summary>
      public static string Purchase_Canceled
      {
         get
         {
            return GetString("Purchase_Canceled");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Congratulations! You have successfully disabled the ads, enjoy the full experience!.
      /// </summary>
      public static string Purchase_Success
      {
         get
         {
            return GetString("Purchase_Success");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to refresh.
      /// </summary>
      public static string Refresh
      {
         get
         {
            return GetString("Refresh");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Pull to Refresh.
      /// </summary>
      public static string Refresh_Pull
      {
         get
         {
            return GetString("Refresh_Pull");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Release to Refresh.
      /// </summary>
      public static string Refresh_Release
      {
         get
         {
            return GetString("Refresh_Release");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Remove.
      /// </summary>
      public static string Remove
      {
         get
         {
            return GetString("Remove");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Remove from favorites.
      /// </summary>
      public static string RemoveFromFavorites
      {
         get
         {
            return GetString("RemoveFromFavorites");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Are you sure that you want to remove this source?.
      /// </summary>
      public static string RemoveSourceConfirmation
      {
         get
         {
            return GetString("RemoveSourceConfirmation");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to LeftToRight.
      /// </summary>
      public static string ResourceFlowDirection
      {
         get
         {
            return GetString("ResourceFlowDirection");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to en-US.
      /// </summary>
      public static string ResourceLanguage
      {
         get
         {
            return GetString("ResourceLanguage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sample Runtime Property Value.
      /// </summary>
      public static string SampleProperty
      {
         get
         {
            return GetString("SampleProperty");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Save.
      /// </summary>
      public static string Save
      {
         get
         {
            return GetString("Save");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to saved articles.
      /// </summary>
      public static string SavedArticles
      {
         get
         {
            return GetString("SavedArticles");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Saved for Later.
      /// </summary>
      public static string SavedForLater
      {
         get
         {
            return GetString("SavedForLater");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to search.
      /// </summary>
      public static string Search
      {
         get
         {
            return GetString("Search");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Settings.
      /// </summary>
      public static string Settings
      {
         get
         {
            return GetString("Settings");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Share.
      /// </summary>
      public static string Share
      {
         get
         {
            return GetString("Share");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Buffer.
      /// </summary>
      public static string Share_Buffer
      {
         get
         {
            return GetString("Share_Buffer");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Copy Url.
      /// </summary>
      public static string Share_Clipboard
      {
         get
         {
            return GetString("Share_Clipboard");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to E-Mail.
      /// </summary>
      public static string Share_Email
      {
         get
         {
            return GetString("Share_Email");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0}
      ///
      ///{1}.
      /// </summary>
      public static string Share_Email_Body
      {
         get
         {
            return GetString("Share_Email_Body");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to .
      /// </summary>
      public static string Share_Email_Subject
      {
         get
         {
            return GetString("Share_Email_Subject");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Evernote.
      /// </summary>
      public static string Share_Evernote
      {
         get
         {
            return GetString("Share_Evernote");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Instapaper.
      /// </summary>
      public static string Share_Instapaper
      {
         get
         {
            return GetString("Share_Instapaper");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to {0} (via @feedsea).
      /// </summary>
      public static string Share_Link_Message
      {
         get
         {
            return GetString("Share_Link_Message");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to NFC.
      /// </summary>
      public static string Share_NFC
      {
         get
         {
            return GetString("Share_NFC");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to OneNote.
      /// </summary>
      public static string Share_OneNote
      {
         get
         {
            return GetString("Share_OneNote");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Pocket.
      /// </summary>
      public static string Share_Pocket
      {
         get
         {
            return GetString("Share_Pocket");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Login.
      /// </summary>
      public static string Share_Pocket_Internal
      {
         get
         {
            return GetString("Share_Pocket_Internal");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Third party apps.
      /// </summary>
      public static string Share_Pocket_ThirdParty
      {
         get
         {
            return GetString("Share_Pocket_ThirdParty");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to .
      /// </summary>
      public static string Share_Sms_Body
      {
         get
         {
            return GetString("Share_Sms_Body");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Social Networks.
      /// </summary>
      public static string Share_SocialNetworks
      {
         get
         {
            return GetString("Share_SocialNetworks");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Text Message.
      /// </summary>
      public static string Share_TextMessage
      {
         get
         {
            return GetString("Share_TextMessage");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Share via.
      /// </summary>
      public static string ShareVia
      {
         get
         {
            return GetString("ShareVia");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Source Name.
      /// </summary>
      public static string SourceName
      {
         get
         {
            return GetString("SourceName");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Sources.
      /// </summary>
      public static string Sources
      {
         get
         {
            return GetString("Sources");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to subscribers.
      /// </summary>
      public static string Subscribers
      {
         get
         {
            return GetString("Subscribers");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Subscriptions.
      /// </summary>
      public static string Subscriptions
      {
         get
         {
            return GetString("Subscriptions");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Default.
      /// </summary>
      public static string TileMode_Normal
      {
         get
         {
            return GetString("TileMode_Normal");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Semi-Transparent.
      /// </summary>
      public static string TileMode_SemiTransparent
      {
         get
         {
            return GetString("TileMode_SemiTransparent");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Transparent.
      /// </summary>
      public static string TileMode_Transparent
      {
         get
         {
            return GetString("TileMode_Transparent");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Uncategorized.
      /// </summary>
      public static string Uncategorized
      {
         get
         {
            return GetString("Uncategorized");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to welcome.
      /// </summary>
      public static string Welcome
      {
         get
         {
            return GetString("Welcome");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Yes.
      /// </summary>
      public static string Yes
      {
         get
         {
            return GetString("Yes");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Default.
      /// </summary>
      public static string YoutubeClient_Default
      {
         get
         {
            return GetString("YoutubeClient_Default");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to MetroTube.
      /// </summary>
      public static string YoutubeClient_Metrotube
      {
         get
         {
            return GetString("YoutubeClient_Metrotube");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to MyTube.
      /// </summary>
      public static string YoutubeClient_MyTube
      {
         get
         {
            return GetString("YoutubeClient_MyTube");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Other clients (TubeCast, Youtube Official etc...).
      /// </summary>
      public static string YoutubeClient_Other
      {
         get
         {
            return GetString("YoutubeClient_Other");
         }
      }

      /// <summary>
      ///   Looks up a localized string similar to Toib.
      /// </summary>
      public static string YoutubeClient_Toib
      {
         get
         {
            return GetString("YoutubeClient_Toib");
         }
      }

      private static string GetString(string key)
      {
         Windows.ApplicationModel.Resources.ResourceLoader loader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView("AppResources");
         return loader.GetString(key);
      }

   }

}