//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace feedsea.Resources
{
   using System;

   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   internal class Files
   {

      internal Files()
      {
      }

      /// <summary>
      ///   Looks up a localized string similar to &lt;html&gt;
      ///	&lt;head&gt;
      ///		&lt;style type=&quot;text/css&quot;&gt;
      ///			body {
      ///				font-family: Georgia !important;
      ///			}
      ///			
      ///			h2 {
      ///				font-size: 26;
      ///			}
      ///			
      ///			#content {
      ///				font-size: 20 !important;
      ///				text-align: justify;
      ///				margin-top: 15px;
      ///			}
      ///			
      ///			#footer {
      ///				color: #666666;
      ///				margin-top: 15px;
      ///				font-size: 18px;
      ///			}
      ///			
      ///			img {
      ///				width: 100%;
      ///				margin-left: auto;
      ///				margin-right: auto;
      ///			}
      ///			
      ///			a {
      ///				color: #1A74B8;
      ///			}
      ///			
      ///			a:visited {
      ///				color: #1A74B8;
      ///			}
      /// [rest of string was truncated]&quot;;.
      /// </summary>
      internal static string ArticleHtml
      {
         get
         {
            throw new NotImplementedException();
         }
      }

      private static string GetString(string key)
      {
         Windows.ApplicationModel.Resources.ResourceLoader loader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView("Files");
         return loader.GetString(key);
      }

   }

}