//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feedsea.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("feedsea.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Add new category&gt;.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Source.
        /// </summary>
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        public static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day ago.
        /// </summary>
        public static string AgoDay {
            get {
                return ResourceManager.GetString("AgoDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days ago.
        /// </summary>
        public static string AgoDays {
            get {
                return ResourceManager.GetString("AgoDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour ago.
        /// </summary>
        public static string AgoHour {
            get {
                return ResourceManager.GetString("AgoHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string AgoHours {
            get {
                return ResourceManager.GetString("AgoHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute ago.
        /// </summary>
        public static string AgoMinute {
            get {
                return ResourceManager.GetString("AgoMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes ago.
        /// </summary>
        public static string AgoMinutes {
            get {
                return ResourceManager.GetString("AgoMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second ago.
        /// </summary>
        public static string AgoSecond {
            get {
                return ResourceManager.GetString("AgoSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds ago.
        /// </summary>
        public static string AgoSeconds {
            get {
                return ResourceManager.GetString("AgoSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Articles.
        /// </summary>
        public static string AllArticles {
            get {
                return ResourceManager.GetString("AllArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedsea.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string ArticleLayoutType_Normal {
            get {
                return ResourceManager.GetString("ArticleLayoutType_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal without Image.
        /// </summary>
        public static string ArticleLayoutType_NormalNoImage {
            get {
                return ResourceManager.GetString("ArticleLayoutType_NormalNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string ArticleLayoutType_Small {
            get {
                return ResourceManager.GetString("ArticleLayoutType_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small without Image.
        /// </summary>
        public static string ArticleLayoutType_SmallNoImage {
            get {
                return ResourceManager.GetString("ArticleLayoutType_SmallNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Article.
        /// </summary>
        public static string ArticleNavigatePage {
            get {
                return ResourceManager.GetString("ArticleNavigatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string AudioFile_Pause {
            get {
                return ResourceManager.GetString("AudioFile_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string AudioFile_Play {
            get {
                return ResourceManager.GetString("AudioFile_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string AudioFile_Playing {
            get {
                return ResourceManager.GetString("AudioFile_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Top.
        /// </summary>
        public static string BackToTop {
            get {
                return ResourceManager.GetString("BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Explorer.
        /// </summary>
        public static string BrowserSelect_InternetExplorer {
            get {
                return ResourceManager.GetString("BrowserSelect_InternetExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxthon.
        /// </summary>
        public static string BrowserSelect_MaxthonBrowser {
            get {
                return ResourceManager.GetString("BrowserSelect_MaxthonBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia Xpress.
        /// </summary>
        public static string BrowserSelect_NokiaXpress {
            get {
                return ResourceManager.GetString("BrowserSelect_NokiaXpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UC Browser.
        /// </summary>
        public static string BrowserSelect_UCBrowser {
            get {
                return ResourceManager.GetString("BrowserSelect_UCBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Login.
        /// </summary>
        public static string ClickToLogin {
            get {
                return ResourceManager.GetString("ClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Ads.
        /// </summary>
        public static string DisableAds {
            get {
                return ResourceManager.GetString("DisableAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Source.
        /// </summary>
        public static string EditSource {
            get {
                return ResourceManager.GetString("EditSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the source URL.
        /// </summary>
        public static string EnterSourceUrl {
            get {
                return ResourceManager.GetString("EnterSourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the url of the source.
        /// </summary>
        public static string EnterUrlOfSource {
            get {
                return ResourceManager.GetString("EnterUrlOfSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Articles.
        /// </summary>
        public static string FeaturedArticles {
            get {
                return ResourceManager.GetString("FeaturedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string Item_Days_1 {
            get {
                return ResourceManager.GetString("Item_Days_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days (recommended).
        /// </summary>
        public static string Item_Days_3 {
            get {
                return ResourceManager.GetString("Item_Days_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 days.
        /// </summary>
        public static string Item_Days_5 {
            get {
                return ResourceManager.GetString("Item_Days_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        public static string Item_Days_7 {
            get {
                return ResourceManager.GetString("Item_Days_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article list items Layout.
        /// </summary>
        public static string Lbl_ArticleListItemLayout {
            get {
                return ResourceManager.GetString("Lbl_ArticleListItemLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask before marking all articles read.
        /// </summary>
        public static string Lbl_AskBeforeMarkingAllRead {
            get {
                return ResourceManager.GetString("Lbl_AskBeforeMarkingAllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Lbl_Categories {
            get {
                return ResourceManager.GetString("Lbl_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose view.
        /// </summary>
        public static string Lbl_ChooseView {
            get {
                return ResourceManager.GetString("Lbl_ChooseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Mobilizer.
        /// </summary>
        public static string Lbl_ChooseView_Google {
            get {
                return ResourceManager.GetString("Lbl_ChooseView_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Mobilizer without Images.
        /// </summary>
        public static string Lbl_ChooseView_GoogleNoImg {
            get {
                return ResourceManager.GetString("Lbl_ChooseView_GoogleNoImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instapaper Mobilizer.
        /// </summary>
        public static string Lbl_ChooseView_Instapaper {
            get {
                return ResourceManager.GetString("Lbl_ChooseView_Instapaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readability Mobilizer.
        /// </summary>
        public static string Lbl_ChooseView_Readability {
            get {
                return ResourceManager.GetString("Lbl_ChooseView_Readability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open web page.
        /// </summary>
        public static string Lbl_ChooseView_WebPage {
            get {
                return ResourceManager.GetString("Lbl_ChooseView_WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        public static string Lbl_CreateNewCategory {
            get {
                return ResourceManager.GetString("Lbl_CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download full article if there&apos;s only summary using.
        /// </summary>
        public static string Lbl_DownloadArticleIfNoContent {
            get {
                return ResourceManager.GetString("Lbl_DownloadArticleIfNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instapaper.
        /// </summary>
        public static string Lbl_DownloadContent_Instapaper {
            get {
                return ResourceManager.GetString("Lbl_DownloadContent_Instapaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readability.
        /// </summary>
        public static string Lbl_DownloadContent_Readability {
            get {
                return ResourceManager.GetString("Lbl_DownloadContent_Readability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Instapaper.
        /// </summary>
        public static string Lbl_Enable_Instapaper {
            get {
                return ResourceManager.GetString("Lbl_Enable_Instapaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable OneNote.
        /// </summary>
        public static string Lbl_Enable_OneNote {
            get {
                return ResourceManager.GetString("Lbl_Enable_OneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Pocket.
        /// </summary>
        public static string Lbl_Enable_Pocket {
            get {
                return ResourceManager.GetString("Lbl_Enable_Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Live Tiles.
        /// </summary>
        public static string Lbl_EnableLiveTiles {
            get {
                return ResourceManager.GetString("Lbl_EnableLiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide AppBar on Article Page.
        /// </summary>
        public static string Lbl_HideAppBarArticlePage {
            get {
                return ResourceManager.GetString("Lbl_HideAppBarArticlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide AppBar on Main Feed.
        /// </summary>
        public static string Lbl_HideAppBarMainPage {
            get {
                return ResourceManager.GetString("Lbl_HideAppBarMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What browser would you like to open article links on?.
        /// </summary>
        public static string Lbl_LinkBrowserSelect {
            get {
                return ResourceManager.GetString("Lbl_LinkBrowserSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tiles.
        /// </summary>
        public static string Lbl_LiveTiles {
            get {
                return ResourceManager.GetString("Lbl_LiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From which category should articles be loaded when the app is started?.
        /// </summary>
        public static string Lbl_LoadCategoryOnLoad {
            get {
                return ResourceManager.GetString("Lbl_LoadCategoryOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Lbl_Login {
            get {
                return ResourceManager.GetString("Lbl_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark article read when opened.
        /// </summary>
        public static string Lbl_MarkArticleReadWhenOpened {
            get {
                return ResourceManager.GetString("Lbl_MarkArticleReadWhenOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark articles read on feed scroll.
        /// </summary>
        public static string Lbl_MarkReadOnFeedScroll {
            get {
                return ResourceManager.GetString("Lbl_MarkReadOnFeedScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: More internet connection usage while scrolling..
        /// </summary>
        public static string Lbl_MarkReadOnFeedScroll_Warning {
            get {
                return ResourceManager.GetString("Lbl_MarkReadOnFeedScroll_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category name.
        /// </summary>
        public static string Lbl_NewCategoryName {
            get {
                return ResourceManager.GetString("Lbl_NewCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open YouTube links on MetroTube.
        /// </summary>
        public static string Lbl_OpenYoutubeOnMetroTube {
            get {
                return ResourceManager.GetString("Lbl_OpenYoutubeOnMetroTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Lbl_Password {
            get {
                return ResourceManager.GetString("Lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Lbl_PhoneSettings {
            get {
                return ResourceManager.GetString("Lbl_PhoneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Lbl_Search {
            get {
                return ResourceManager.GetString("Lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string Lbl_SearchResults {
            get {
                return ResourceManager.GetString("Lbl_SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Lbl_SettingsPage_About {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Lbl_SettingsPage_About_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Lbl_SettingsPage_Appearance {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change app theme, feed list style and more..
        /// </summary>
        public static string Lbl_SettingsPage_Appearance_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Appearance_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Ads.
        /// </summary>
        public static string Lbl_SettingsPage_DisableAds {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_DisableAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Ads shown in the app..
        /// </summary>
        public static string Lbl_SettingsPage_DisableAds_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_DisableAds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Lbl_SettingsPage_Feedback {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an email with feedback or bug reports..
        /// </summary>
        public static string Lbl_SettingsPage_Feedback_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Feedback_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Lbl_SettingsPage_General {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide read articles, download content and other reading settings..
        /// </summary>
        public static string Lbl_SettingsPage_General_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_General_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Tiles.
        /// </summary>
        public static string Lbl_SettingsPage_LiveTiles {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_LiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable live tiles and change the appearance..
        /// </summary>
        public static string Lbl_SettingsPage_LiveTiles_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_LiveTiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Lbl_SettingsPage_Logout {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out from Feedly..
        /// </summary>
        public static string Lbl_SettingsPage_Logout_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Logout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party.
        /// </summary>
        public static string Lbl_SettingsPage_ThirdParty {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instapaper, Pocket, OneNote and more..
        /// </summary>
        public static string Lbl_SettingsPage_ThirdParty_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_ThirdParty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uservoice.
        /// </summary>
        public static string Lbl_SettingsPage_Uservoice {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Uservoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback and support page..
        /// </summary>
        public static string Lbl_SettingsPage_Uservoice_Description {
            get {
                return ResourceManager.GetString("Lbl_SettingsPage_Uservoice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show articles from oldest to newest.
        /// </summary>
        public static string Lbl_ShowOldestToNewest {
            get {
                return ResourceManager.GetString("Lbl_ShowOldestToNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Phone Tray at top of Screen.
        /// </summary>
        public static string Lbl_ShowPhoneTrayAtTop {
            get {
                return ResourceManager.GetString("Lbl_ShowPhoneTrayAtTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show read articles on feed.
        /// </summary>
        public static string Lbl_ShowReadArticlesOnMainScreen {
            get {
                return ResourceManager.GetString("Lbl_ShowReadArticlesOnMainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show read if there are no unread articles.
        /// </summary>
        public static string Lbl_ShowReadIfNoUnread {
            get {
                return ResourceManager.GetString("Lbl_ShowReadIfNoUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        public static string Lbl_Theme {
            get {
                return ResourceManager.GetString("Lbl_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Lbl_Theme_Dark {
            get {
                return ResourceManager.GetString("Lbl_Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Lbl_Theme_Default {
            get {
                return ResourceManager.GetString("Lbl_Theme_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how you want your tiles to be presented..
        /// </summary>
        public static string Lbl_TileMode {
            get {
                return ResourceManager.GetString("Lbl_TileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL, Title or #topic.
        /// </summary>
        public static string Lbl_UrlTitleOrTopic {
            get {
                return ResourceManager.GetString("Lbl_UrlTitleOrTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username (or Email).
        /// </summary>
        public static string Lbl_Username {
            get {
                return ResourceManager.GetString("Lbl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Lbl_Version {
            get {
                return ResourceManager.GetString("Lbl_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What client would you like to open YouTube videos on?.
        /// </summary>
        public static string Lbl_YoutubeClient {
            get {
                return ResourceManager.GetString("Lbl_YoutubeClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred the last time you ran Feedsea, do you want to report us?.
        /// </summary>
        public static string LittleWatson_Message {
            get {
                return ResourceManager.GetString("LittleWatson_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string LittleWatson_Title {
            get {
                return ResourceManager.GetString("LittleWatson_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout from your Feedly account? All Feedsea settings will be lost..
        /// </summary>
        public static string Logout_Message {
            get {
                return ResourceManager.GetString("Logout_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all read.
        /// </summary>
        public static string MarkAllRead {
            get {
                return ResourceManager.GetString("MarkAllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark articles read.
        /// </summary>
        public static string MarkArticlesRead {
            get {
                return ResourceManager.GetString("MarkArticlesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Read.
        /// </summary>
        public static string MarkRead {
            get {
                return ResourceManager.GetString("MarkRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark Unread.
        /// </summary>
        public static string MarkUnread {
            get {
                return ResourceManager.GetString("MarkUnread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedsea is developed by.
        /// </summary>
        public static string Msg_About_DevelopedBy {
            get {
                return ResourceManager.GetString("Msg_About_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eric Mackrodt.
        /// </summary>
        public static string Msg_About_DeveloperName {
            get {
                return ResourceManager.GetString("Msg_About_DeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow on Twitter.
        /// </summary>
        public static string Msg_About_FollowTwitter {
            get {
                return ResourceManager.GetString("Msg_About_FollowTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the app.
        /// </summary>
        public static string Msg_About_RateApp {
            get {
                return ResourceManager.GetString("Msg_About_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an email.
        /// </summary>
        public static string Msg_About_SendEmail {
            get {
                return ResourceManager.GetString("Msg_About_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to give a feedback or tell me something else?.
        /// </summary>
        public static string Msg_About_SendFeedbackMessage {
            get {
                return ResourceManager.GetString("Msg_About_SendFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m using and recommend Feedsea as a news reader on Windows Phone (@feedsea).
        /// </summary>
        public static string Msg_About_ShareMessage {
            get {
                return ResourceManager.GetString("Msg_About_ShareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share with your friends.
        /// </summary>
        public static string Msg_About_ShareWithFriends {
            get {
                return ResourceManager.GetString("Msg_About_ShareWithFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Live Tile is already pinned..
        /// </summary>
        public static string Msg_AlreadyPinned {
            get {
                return ResourceManager.GetString("Msg_AlreadyPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save a source without a title..
        /// </summary>
        public static string MSG_CannotSaveSourceWithoutTitle {
            get {
                return ResourceManager.GetString("MSG_CannotSaveSourceWithoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry&lt;br /&gt;There was a problem loading the login page, press back to retry or try again later..
        /// </summary>
        public static string Msg_CouldntLoadLoginPage {
            get {
                return ResourceManager.GetString("Msg_CouldntLoadLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load source, please verify the URL..
        /// </summary>
        public static string MSG_CouldntLoadSource {
            get {
                return ResourceManager.GetString("MSG_CouldntLoadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to enable pocket?.
        /// </summary>
        public static string Msg_Enable_Pocket {
            get {
                return ResourceManager.GetString("Msg_Enable_Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid URL..
        /// </summary>
        public static string MSG_EnterValidURL {
            get {
                return ResourceManager.GetString("MSG_EnterValidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you are new here, add sources to start reading your news..
        /// </summary>
        public static string Msg_Greetings_Message {
            get {
                return ResourceManager.GetString("Msg_Greetings_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Msg_Greetings_Title {
            get {
                return ResourceManager.GetString("Msg_Greetings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter a valid URL before loading..
        /// </summary>
        public static string MSG_HaveToEnterURLSourceBeforeLoading {
            get {
                return ResourceManager.GetString("MSG_HaveToEnterURLSourceBeforeLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart the app for these settings to take effect..
        /// </summary>
        public static string Msg_HaveToRestartToTakeEffect {
            get {
                return ResourceManager.GetString("Msg_HaveToRestartToTakeEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedsea received an unexpected response from Feedly. This might mean that Feedly is under maintenance or that you&apos;re connected to a network that needs authentication, have blocked content or uses a proxy server. If none of those are the case and this problem persists, try to logoff and login again..
        /// </summary>
        public static string Msg_HtmlResponse_Message {
            get {
                return ResourceManager.GetString("Msg_HtmlResponse_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected response from Feedly.
        /// </summary>
        public static string Msg_HtmlResponse_Title {
            get {
                return ResourceManager.GetString("Msg_HtmlResponse_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark all current articles read?.
        /// </summary>
        public static string MSG_MarkCurrentArticlesReadConfirm {
            get {
                return ResourceManager.GetString("MSG_MarkCurrentArticlesReadConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing new right now. Try refreshing the feed..
        /// </summary>
        public static string Msg_NoArticlesAvailable {
            get {
                return ResourceManager.GetString("Msg_NoArticlesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t establish a connection right now. Verify your connection or try again later..
        /// </summary>
        public static string MSG_NoConnection {
            get {
                return ResourceManager.GetString("MSG_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that you&apos;re new here, try adding new sources..
        /// </summary>
        public static string Msg_NoSourcesAvailable {
            get {
                return ResourceManager.GetString("Msg_NoSourcesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinning Live Tile.
        /// </summary>
        public static string Msg_PinningLiveTile {
            get {
                return ResourceManager.GetString("Msg_PinningLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will remove the category but won&apos;t remove the sources within it. Are you sure you want to proceed?.
        /// </summary>
        public static string MSG_RemoveCategoryConfirmation {
            get {
                return ResourceManager.GetString("MSG_RemoveCategoryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this article from saved articles?.
        /// </summary>
        public static string MSG_RemoveFromSaved {
            get {
                return ResourceManager.GetString("MSG_RemoveFromSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending article to Instapaper.
        /// </summary>
        public static string Msg_SendingTo_Instapaper {
            get {
                return ResourceManager.GetString("Msg_SendingTo_Instapaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article sent to Instapaper successfully.
        /// </summary>
        public static string Msg_SendingTo_Instapaper_Done {
            get {
                return ResourceManager.GetString("Msg_SendingTo_Instapaper_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending article to OneNote.
        /// </summary>
        public static string Msg_SendingTo_OneNote {
            get {
                return ResourceManager.GetString("Msg_SendingTo_OneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article sent to OneNote successfully.
        /// </summary>
        public static string Msg_SendingTo_OneNote_Done {
            get {
                return ResourceManager.GetString("Msg_SendingTo_OneNote_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending article to Pocket.
        /// </summary>
        public static string Msg_SendingTo_Pocket {
            get {
                return ResourceManager.GetString("Msg_SendingTo_Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article sent to Pocket successfully.
        /// </summary>
        public static string Msg_SendingTo_Pocket_Done {
            get {
                return ResourceManager.GetString("Msg_SendingTo_Pocket_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already a source with the same URL, verify if you are not trying to add it again or try changing the title..
        /// </summary>
        public static string MSG_ThereIsSourceSameURL {
            get {
                return ResourceManager.GetString("MSG_ThereIsSourceSameURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Live Tiles.
        /// </summary>
        public static string Msg_UpdatingLiveTiles {
            get {
                return ResourceManager.GetString("Msg_UpdatingLiveTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password, please try again..
        /// </summary>
        public static string Msg_WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("Msg_WrongUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to load a source before saving..
        /// </summary>
        public static string MSG_YouHaveToLoadSourceBeforeSaving {
            get {
                return ResourceManager.GetString("MSG_YouHaveToLoadSourceBeforeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart the app to apply the theme. Click here to close the app..
        /// </summary>
        public static string Msg_YouHaveToRestartToApplyTheme {
            get {
                return ResourceManager.GetString("Msg_YouHaveToRestartToApplyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to news.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in the Browser.
        /// </summary>
        public static string OpenInBrowser {
            get {
                return ResourceManager.GetString("OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to Start screen.
        /// </summary>
        public static string PinToStartScreen {
            get {
                return ResourceManager.GetString("PinToStartScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already purchased this product..
        /// </summary>
        public static string Purchase_AlreadyPurchased {
            get {
                return ResourceManager.GetString("Purchase_AlreadyPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purchase was canceled..
        /// </summary>
        public static string Purchase_Canceled {
            get {
                return ResourceManager.GetString("Purchase_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully disabled the ads, enjoy the full experience!.
        /// </summary>
        public static string Purchase_Success {
            get {
                return ResourceManager.GetString("Purchase_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull to Refresh.
        /// </summary>
        public static string Refresh_Pull {
            get {
                return ResourceManager.GetString("Refresh_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release to Refresh.
        /// </summary>
        public static string Refresh_Release {
            get {
                return ResourceManager.GetString("Refresh_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string RemoveFromFavorites {
            get {
                return ResourceManager.GetString("RemoveFromFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to remove this source?.
        /// </summary>
        public static string RemoveSourceConfirmation {
            get {
                return ResourceManager.GetString("RemoveSourceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saved articles.
        /// </summary>
        public static string SavedArticles {
            get {
                return ResourceManager.GetString("SavedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved for Later.
        /// </summary>
        public static string SavedForLater {
            get {
                return ResourceManager.GetString("SavedForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer.
        /// </summary>
        public static string Share_Buffer {
            get {
                return ResourceManager.GetString("Share_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Url.
        /// </summary>
        public static string Share_Clipboard {
            get {
                return ResourceManager.GetString("Share_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string Share_Email {
            get {
                return ResourceManager.GetString("Share_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///
        ///{1}.
        /// </summary>
        public static string Share_Email_Body {
            get {
                return ResourceManager.GetString("Share_Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Share_Email_Subject {
            get {
                return ResourceManager.GetString("Share_Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evernote.
        /// </summary>
        public static string Share_Evernote {
            get {
                return ResourceManager.GetString("Share_Evernote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instapaper.
        /// </summary>
        public static string Share_Instapaper {
            get {
                return ResourceManager.GetString("Share_Instapaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (via @feedsea).
        /// </summary>
        public static string Share_Link_Message {
            get {
                return ResourceManager.GetString("Share_Link_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NFC.
        /// </summary>
        public static string Share_NFC {
            get {
                return ResourceManager.GetString("Share_NFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote.
        /// </summary>
        public static string Share_OneNote {
            get {
                return ResourceManager.GetString("Share_OneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket.
        /// </summary>
        public static string Share_Pocket {
            get {
                return ResourceManager.GetString("Share_Pocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Share_Pocket_Internal {
            get {
                return ResourceManager.GetString("Share_Pocket_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third party apps.
        /// </summary>
        public static string Share_Pocket_ThirdParty {
            get {
                return ResourceManager.GetString("Share_Pocket_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Share_Sms_Body {
            get {
                return ResourceManager.GetString("Share_Sms_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Networks.
        /// </summary>
        public static string Share_SocialNetworks {
            get {
                return ResourceManager.GetString("Share_SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Message.
        /// </summary>
        public static string Share_TextMessage {
            get {
                return ResourceManager.GetString("Share_TextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share via.
        /// </summary>
        public static string ShareVia {
            get {
                return ResourceManager.GetString("ShareVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribers.
        /// </summary>
        public static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string TileMode_Normal {
            get {
                return ResourceManager.GetString("TileMode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-Transparent.
        /// </summary>
        public static string TileMode_SemiTransparent {
            get {
                return ResourceManager.GetString("TileMode_SemiTransparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        public static string TileMode_Transparent {
            get {
                return ResourceManager.GetString("TileMode_Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        public static string Uncategorized {
            get {
                return ResourceManager.GetString("Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string YoutubeClient_Default {
            get {
                return ResourceManager.GetString("YoutubeClient_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetroTube.
        /// </summary>
        public static string YoutubeClient_Metrotube {
            get {
                return ResourceManager.GetString("YoutubeClient_Metrotube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyTube.
        /// </summary>
        public static string YoutubeClient_MyTube {
            get {
                return ResourceManager.GetString("YoutubeClient_MyTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other clients (TubeCast, Youtube Official etc...).
        /// </summary>
        public static string YoutubeClient_Other {
            get {
                return ResourceManager.GetString("YoutubeClient_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toib.
        /// </summary>
        public static string YoutubeClient_Toib {
            get {
                return ResourceManager.GetString("YoutubeClient_Toib", resourceCulture);
            }
        }
    }
}
