//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedseaWebSite.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeedseaWebSite.App_GlobalResources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a Human?.
        /// </summary>
        public static string AreYouHuman {
            get {
                return ResourceManager.GetString("AreYouHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available for.
        /// </summary>
        public static string AvailableFor {
            get {
                return ResourceManager.GetString("AvailableFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha answer cannot be empty..
        /// </summary>
        public static string CaptchaEmpty {
            get {
                return ResourceManager.GetString("CaptchaEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        public static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with your request, try again later..
        /// </summary>
        public static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong..
        /// </summary>
        public static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured in.
        /// </summary>
        public static string FeaturedIn {
            get {
                return ResourceManager.GetString("FeaturedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to open a link? You can choose your favorite browser! Want to open a YouTube video? Choose your favorite app to do so!.
        /// </summary>
        public static string Features_ChooseApp_Message {
            get {
                return ResourceManager.GetString("Features_ChooseApp_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your favorite app for other services.
        /// </summary>
        public static string Features_ChooseApp_Title {
            get {
                return ResourceManager.GetString("Features_ChooseApp_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go directly to your favorite feed without having to go through menus, options, screens or anything else..
        /// </summary>
        public static string Features_StraightToNews_Message {
            get {
                return ResourceManager.GetString("Features_StraightToNews_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight to your news!.
        /// </summary>
        public static string Features_StraightToNews_Title {
            get {
                return ResourceManager.GetString("Features_StraightToNews_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your articles shown in a really visual way, for you to get the most of the information..
        /// </summary>
        public static string Features_Visual_Message {
            get {
                return ResourceManager.GetString("Features_Visual_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely visual.
        /// </summary>
        public static string Features_Visual_Title {
            get {
                return ResourceManager.GetString("Features_Visual_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug.
        /// </summary>
        public static string FeedbackType_Bug {
            get {
                return ResourceManager.GetString("FeedbackType_Bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string FeedbackType_Other {
            get {
                return ResourceManager.GetString("FeedbackType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one.
        /// </summary>
        public static string FeedbackType_SelectOne {
            get {
                return ResourceManager.GetString("FeedbackType_SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string FeedbackType_Suggestion {
            get {
                return ResourceManager.GetString("FeedbackType_Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A straightforward Feedly client for Windows Phone!.
        /// </summary>
        public static string Header1_Message {
            get {
                return ResourceManager.GetString("Header1_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedsea is an app focused on what really matters. Your News..
        /// </summary>
        public static string Header1_SubMessage {
            get {
                return ResourceManager.GetString("Header1_SubMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, it&apos;s the first thing it brings when opened, you won&apos;t have to navigate throught a lot of menus to get where you want!.
        /// </summary>
        public static string Header1_Text {
            get {
                return ResourceManager.GetString("Header1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to test it?.
        /// </summary>
        public static string Header2_Message {
            get {
                return ResourceManager.GetString("Header2_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the closed beta today by filling the beta program form!.
        /// </summary>
        public static string Header2_SubMessage {
            get {
                return ResourceManager.GetString("Header2_SubMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After that you&apos;ll be added to the beta, then you&apos;ll be able to test the app and send feedback!.
        /// </summary>
        public static string Header2_Text {
            get {
                return ResourceManager.GetString("Header2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect captcha answer..
        /// </summary>
        public static string IncorrectCaptcha {
            get {
                return ResourceManager.GetString("IncorrectCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Lang_enUS {
            get {
                return ResourceManager.GetString("Lang_enUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Lang_ptBR {
            get {
                return ResourceManager.GetString("Lang_ptBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rio de Janeiro - Brazil.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string MenuItem_Feedback {
            get {
                return ResourceManager.GetString("MenuItem_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuItem_Home {
            get {
                return ResourceManager.GetString("MenuItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Beta.
        /// </summary>
        public static string MenuItem_JoinBeta {
            get {
                return ResourceManager.GetString("MenuItem_JoinBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email associated with your phone.
        /// </summary>
        public static string MicrosoftAccount_Hint {
            get {
                return ResourceManager.GetString("MicrosoftAccount_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help/Suggestion.
        /// </summary>
        public static string NeedHelpSuggestion {
            get {
                return ResourceManager.GetString("NeedHelpSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string PageTitle_Feedback {
            get {
                return ResourceManager.GetString("PageTitle_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Beta.
        /// </summary>
        public static string PageTitle_JoinBeta {
            get {
                return ResourceManager.GetString("PageTitle_JoinBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and powerful..
        /// </summary>
        public static string SimpleYetPowerful {
            get {
                return ResourceManager.GetString("SimpleYetPowerful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedsea.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eric Mackrodt.
        /// </summary>
        public static string Social_Author {
            get {
                return ResourceManager.GetString("Social_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) Eric Mackrodt 2014.
        /// </summary>
        public static string Social_Copyright {
            get {
                return ResourceManager.GetString("Social_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A straightforward Feedly client for Windows Phone..
        /// </summary>
        public static string Social_Description {
            get {
                return ResourceManager.GetString("Social_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedsea.
        /// </summary>
        public static string Social_Title {
            get {
                return ResourceManager.GetString("Social_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A straightforward Feedly client for Windows Phone..
        /// </summary>
        public static string Straightforward {
            get {
                return ResourceManager.GetString("Straightforward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re going to be added to the beta program within a few hours and will receive an email with the app download link..
        /// </summary>
        public static string Success_BetaSent_Message {
            get {
                return ResourceManager.GetString("Success_BetaSent_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your request was sent successfully..
        /// </summary>
        public static string Success_BetaSent_Title {
            get {
                return ResourceManager.GetString("Success_BetaSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feeback was sent successfully. Thank you very much!.
        /// </summary>
        public static string Success_Feedback_Message {
            get {
                return ResourceManager.GetString("Success_Feedback_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        public static string Success_Feedback_Title {
            get {
                return ResourceManager.GetString("Success_Feedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did you hear about Feedsea?.
        /// </summary>
        public static string WhereDidYouHear {
            get {
                return ResourceManager.GetString("WhereDidYouHear", resourceCulture);
            }
        }
    }
}
